### ISSUE TITLE
Source Files in Linked Directories

### ISSUE THREAD

**Issue by kassbohm** [melissawm/sphinx-tags#28]
see comment below for my point.

**Comment by kassbohm** [comment]
Using the readthedocs theme...
there are two issues for me:

1. If I place a tag in more than one source files: I still only see **exactly** one entry for this tag in the tagsindex.rst.
2. I do not see the tagsindex-toctree in the sidebar.

Any suggestions?

**Comment by kassbohm** [comment]
Hi Melissa (if that's your name).

I attached an very small example of what I think is unintended behaviour:

Expectations:

- tag2 appearing **2 times** in `tag2.html`
- tag2 being counted **twice** in `tagsindex.html`

Observations:

- tag2 appearing **1 time** in `tag2.html`
- tag2 being counted **once** in `tagsindex.html`

[Tags.zip](https://github.com/melissawm/sphinx-tags/files/9795232/Tags.zip)

**Comment by melissawm** [comment]
Hi @kassbohm - thanks for opening the issue. You are right - let me try and investigate what is happening here, but looks like a bug.

**Comment by kassbohm** [comment]
Thanks for getting back. Take your time.

**Comment by kassbohm** [comment]
Hi @melissawm.

Should I use a workaround? Or will you adress this issue any time soon?

**Comment by melissawm** [comment]
Hi @kassbohm - really sorry for the delay! Can you still reproduce this? I can't seem to anymore - I see tag2 being counted twice in `_tagsindex.html` and 2 pages listed under `tag2.html`. Let me know what you can observe!

**Comment by kassbohm** [comment]
Hello,

There is a directory called LinkedDir.

There is a difference between:

1) using this directory **as is**:
source/LinkedDir

![Dir_as_Dir](https://user-images.githubusercontent.com/1640233/212919074-11d13a43-c05f-4a46-895a-172a34b0abd1.png)


2) using only **a link** to this directory, with the actual directory residing elsewhere, e.g.:
source/LinkedDir -> ../../LinkedDir/

![Dir_as_Link](https://user-images.githubusercontent.com/1640233/212917766-1008ac19-46e2-4792-987c-a91b6e6e0158.png)

Using 1) There are **two files** found with "tag2".
Using 2) There is only **one file** found with "tag2".

**Comment by melissawm** [comment]
Got it! Let me try and see what's up. Thanks again!

**Comment by kassbohm** [comment]
Any news on this?

**Comment by kassbohm** [comment]
This solves the example I provided above. But I am afraid it does **not** solve the general problem with linked directories...

I have attached a **new Tags.zip**, which again leads to incorrect behaviour.

[Tags.zip](https://github.com/melissawm/sphinx-tags/files/10509437/Tags.zip)

**Comment by melissawm** [comment]
Thanks - I list I have a clue now, will try to investigate!
