### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by melissawm** [melissawm/sphinx-tags#38]
For now, the documentation itself serves as tests for the current features, but this doesn't test (for example) the use of symlinked directories. We should have a proper test suite for the extension.

**Comment by JWCook** [comment]
I think there are two options for this:
1. Unit test: mock everything (Sphinx app and config objects, etc.), and test individual classes and functions
2. Integration test: Use a full build environment with some test source files, and compare output

Option 1 would probably be more straightforward to write (without much knowledge of Sphinx internals), but option 2 would be more thorough. I'm not sure how best to set up a build environment for testing, but I'm curious, so I'm willing to look into it.

Sphinx has a `sphinx.testing` subpackage that doesn't appear to be documented, but looks potentially useful: https://github.com/sphinx-doc/sphinx/tree/master/sphinx/testing

**Comment by JWCook** [comment]
`sphinx.testing` looks like the best option for most of the things we would want to test. If that sounds good to you, I'll plan on getting that started with a few basic tests.

**Comment by melissawm** [comment]
I'd be happy to see that, thanks!
