### ISSUE TITLE
Normalize tag URLs

### ISSUE THREAD

**Issue by JWCook** [melissawm/sphinx-tags#56]
Here's an idea for a small cosmetic improvement (related to #39): Make tag URLs with whitespace or other non-alphanumeric characters more easily human-readable. This could be done by normalizing them the same way Markdown normalizes heading anchor links.

# Markdown anchors
For example, if you have a Markdown heading like:
```md
# Title: subtitle (parenthetical)
```
The anchor link generated for that will look like:
```py
page.html#title-subtitle-parenthetical
```
Instead of:
```py
page.html#title%3A%20subtitle%20%28parenthetical%29
```

I can't find the exact rules in the [Commonmark spec](https://spec.commonmark.org/0.30/), but it looks like it just replaces spaces with hyphens, and strips out any other special characters. I am guessing it does this mainly to make it a [valid HTML attribute](https://www.w3.org/TR/2011/WD-html5-20110525/syntax.html#attributes-0) (`<a id="...">`), but has the side effect of making a more readable link.

# Tag URLs
We could do the same for tag URLs, so they always appear without any urlencoded characters, like:
```py
https://site.com/tags/normalized-tag-label.html
```

I could submit a PR for that if you'd like.

**Comment by melissawm** [comment]
I like that, feel free to do it 🚀
