### ISSUE TITLE
Publish releases based on git tags

### ISSUE THREAD

**Issue by JWCook** [melissawm/sphinx-tags#72]
Something you may find useful is to automatically build and publish packages to PyPI based on git tags. A few reasons you might like to do that are:
* Lets you take advantage of PyPI [Trusted Publishers](https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/) (instead of API tokens or username/password)
* Gives you the option of giving other contributors the ability to publish releases (with tag push permissions on the repo)
* Makes sure a tagged commit is always the same one used to build a given PyPI release (relevant for any downstream builds for other packaging systems)

You don't necessarily need those things for a smaller project like this, but if you're interested I can help set that up with GitHub Actions. Instructions for setting that up on the PyPI end [are here](https://docs.pypi.org/trusted-publishers/adding-a-publisher/).

**Comment by melissawm** [comment]
I have zero (ok maybe 0.1 now 😄 ) experience with releasing, so I'd happily take that advice. Would you be willing to set that up? Thanks!!

**Comment by melissawm** [comment]
I'd like to release 0.3.0 sooner rather than later because we want to use this project for the sprint tomorrow, but this is something I'll definitely want for the next release. So - I'll read the docs and try to set that up afterwards. Thanks again!
